film/Movies/urls.py
from django.contrib import admin
from django.urls import path, include

from Movies import views

app_name="Movies"

urlpatterns = [
    # path('',views.home,name="home"),
    path('',views.movieListview.as_view(),name="home"),

    # path('addfilm/',views.addfilm,name="addfilm"),
    path('addfilm/',views.createview.as_view(),name="addfilm"),

    # path('viewdetails/<int:p>',views.viewdetails,name='viewdetails'),
    path('viewdetails/<int:pk>',views.Moviedetailview.as_view(),name="viewdetails"),

    # path('deletemovie/<int:p>',views.deletemovie,name='deletemovie'),
    path('deletemovie/<int:pk>',views.deleteview.as_view(),name='deletemovie'),


    # path('editmovie/<int:p>',views.editmovie,name='editmovie'),
    path('editmovie/<int:pk>',views.updateview.as_view(),name='editmovie'),
]

film/film/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Movies.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

film/Movies/models.py
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=30)
    year = models.IntegerField()
    rating = models.IntegerField()
    desc = models.CharField(max_length=50)
    img=models.ImageField(upload_to='film/img',null=True,blank=True)

film/Movies/forms.py
#Form Definition
from django import forms
from Movies.models import Movie

class Movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

film/Movies/views.py
from django.shortcuts import render
from Movies.models import Movie
from Movies.forms import Movieform
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


# def home(request):
#     m = Movie.objects.all()
#     return render(request, 'home.html',{'m':m})

#CLASS BASED CODE
class movieListview(ListView):
    model=Movie
    template_name="home.html"
    context_object_name="m"

# def addfilm(request):
#     if (request.method == "POST"):
#         t = request.POST['t']
#         y = request.POST['y']
#         r =  request.Post['r']
#         d = request.POST['d']
#         i = request.FILES['i']
#         m = Movie.objects.create(title=t, year=y, rating=r ,desc=d, img=i)
#         m.save()
#         return home(request)
#     return render(request,'addfilm.html')

class createview(CreateView):
    model=Movie
    template_name="addfilm.html"
    fields=['title','year','rating','desc','img']
    success_url = reverse_lazy('Movies:home')


# def viewdetails(request,p):
#     m = Movie.objects.get(id=p)
#     return render(request,'viewdetails.html',{'m':m})

class  Moviedetailview(DetailView):
    model=Movie
    template_name="viewdetails.html"
    context_object_name='m'

# def deletemovie(request,p):
#
#     m = Movie.objects.get(id=p)
#     m.delete()
#     return home(request)

class  deleteview(DeleteView):
    model=Movie
    template_name="deletemovie.html"
    success_url = reverse_lazy('Movies:home')

# def editmovie(request,p):
#     m = Movie.objects.get(id=p)
#     form = Movieform(instance=m)
#     if (request.method == "POST"):
#         form = Movieform(request.POST,request.FILES,instance=m)
#
#         if form.is_valid():
#             form.save()
#             return home(request)
#     return render(request, 'editmovie.html', {'form': form})
class updateview(UpdateView):
    model=Movie
    template_name="editmovie.html"
    fields=['title','year','rating','desc','img']
    success_url = reverse_lazy('Movies:home')

film/templates/addfilm.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container-fluid" style="background:#f48fb1">
  <h2 style="color:green"><i>Add Film here</i></h2>
<form method="POST" class="p-4" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Title</label>
    <input type="text" class="form-control" name="t" placeholder="Enter Title">
  </div>
    <div class="mb-3">
    <label class="form-label">Year</label>
    <input type="number" class="form-control" name="y" placeholder="Enter year">
  </div>
    <div class="mb-3">
    <label class="form-label">Rating</label>
    <input type="number" class="form-control" name="r" placeholder="Enter rating">
  </div>
  <div class="mb-3">
    <label class="form-label">Description</label>
    <input type="text" class="form-control" name="d" placeholder="Enter Description">
  </div>
   <div class="mb-3">
    <label class="form-label">Image</label>
    <input type="file" class="form-control" name="i" placeholder="Enter image">
  </div>
    <div class="mb-3">
    <input type="submit" class="btn btn-primary">
  </div>
</form></div>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit">
</form>
{% endblock %}

film/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
  </head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background:#6f42c1">
  <div class="container-fluid">
      <a class="navbar-brand fs-1" href="#"><b>Online Movie Store</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <br>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link fs-4" aria-current="page" href="{% url 'Movies:home' %}" style="color:white">Home</a>
        </li>
      </ul>
       <div class="d-flex nav-item">
          <a class="btn btn-outline-light bg-dark" href="{% url 'Movies:addfilm' %}">ADD MOVIE</a>
        </div>

    </div>
  </div>
</nav>


<br>
{% block content %}
{% endblock %}


</body>
</html>

film/templates/deletemovie.html
{% extends 'base.html'%}
<form method="POST">
  {% csrf_token %}
  Are you want to delete this movie??
  <input type="submit"></form>

film/templates/editmovie.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<div class="container" style="background:lavender">
    <h2 style="color:brown"><i>Edit Movie</i></h2>
    <br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{form.as_table}}
</table>
<input type="submit" class="btn btn-danger">
</form></div>
{% endblock%}

film/templates/home.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {%for i in m %}
        <div class=" col-md-3" style="height:450px">
            <div class="card" style="background:#b39ddb">
                <img src="{{i.img.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="color:green">
                 <h5 class="card-title" style="text-transform:uppercase;">{{i.title}}({{i.year}})</h5>
                    <p class="card-text">RATING:{{i.rating}}</p>
                <a href="{% url 'Movies:viewdetails' i.id %}" class="btn btn-outline-light" style="background:#1a237e">VIEW</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

film/templates/viewdetails.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container">
<h1 style="color:blue; text-decoration:underline"><i>Movie Details</i></h1>
<br>
    <div class="row">
        <div class=" col-md-3 " >
            <div class="card" style="background:#f8bbd0">
                <img src="{{m.img.url}}" class="card-img-top" alt="..." height="250px">
                <div class="card-body">
                 <h5 class="card-title">{{m.title}}({{m.year}})</h5>
                    <p class="card-text">RATING:{{m.rating}}</p>
                    <p class="card-text">DESCRIPTION:{{m.desc}}</p>
                <a href="{% url 'Movies:editmovie' m.id %}" class="btn" style="background:#00897b">EDIT</a>
                <a href="{% url 'Movies:deletemovie' m.id %}" class="btn" style="background:#eeff41">DELETE</a>
                </div>
            </div>
        </div>
    </div>
</div></div>



<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div class=" col-md-6 " >-->
<!--            <img src="{{m.img.url}}" class="img-top" alt="..." height="400px" width="500px">-->
<!--        </div>-->
<!--        <div class=" col-md-6 ">-->
<!--            <h5 class="card-title" style="text-transform:uppercase;"><b>{{m.title}}({{m.year}})</b></h5><br>-->
<!--            <p class="card-text">RATING:{{m.rating}}</p>-->
<!--                    <p class="card-text"><b>DESCRIPTION:</b><i>{{m.desc}}</i></p>-->
<!--                <a href="{% url 'Movies:editmovie' m.id %}" class="btn btn-warning">EDIT</a>-->
<!--                <a href="{% url 'Movies:deletemovie' m.id %}" class="btn btn-danger">DELETE</a>-->
<!--        </div>-->

<!--    </div>-->
<!--</div>-->
{% endblock %}