ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path

from cart import views

app_name="cart"
urlpatterns = [
    path('add_cart/<int:p>', views.add_cart, name="add_cart"),
    path('cartview/', views.cartview, name="cartview"),
    path('cart_remove/<int:p>', views.cart_remove, name="cart_remove"),
    path('delete_cart/<int:p>',views.delete_cart,name="delete_cart"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views

app_name = "search"

urlpatterns = [
    path('', views.searchresult, name="searchresult"),
]

ecommerce/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('', views.home,name="home"),
    path('allproducts/<slug:e>',views.allproducts,name="allproducts"),
    path('viewproduct/<slug:e>',views.viewproduct,name="viewproduct"),
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateField(auto_now_add=True)
    active=models.BooleanField(default=True)

    def __str__(self):
        return self.products.name


    def subtotal(self):
        return self.quantity*self.products.price

class Account(models.Model):
    Acctnumber = models.CharField(max_length=30)
    Accttype = models.CharField(max_length=30)
    Amount = models.IntegerField()

    def __str__(self):
        return self.Acctnumber

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    noofitems=models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
# class Subtotal(models.Model):

ecommerce/cart/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from cart.models import Cart
from shop.models import Product
from cart.models import Account, Order


@login_required
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
        cart.save()

    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,products=product,quantity=1)
        cart.save()
    return redirect('cart:cartview')

def cartview(request):
    total=0
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price
    except Cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cart,'total':total})
@login_required()
def cart_remove(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')

def delete_cart(request,p):
    product = Product.objects.get(id=p)
    user = request.user
    try:
        cart = Cart.objects.get(products=product, user=user)
        cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')
@login_required()
def orderform(request):
    total=0
    if(request.method=="POST"):
        a =request.POST['a']
        p = request.POST['p']
        c = request.POST['c']
        u=request.user
        cart=Cart.objects.filter(user=u)
        for i in cart:
           total+=i.quantity*i.products.price
           ac=Account.objects.get(Acctnumber=c)
        if (ac.Amount >= total):
             ac.Amount=ac.Amount-total
             ac.save()

             for i in cart:
                 o=Order.objects.create(user=u,products=i.products,address=a,phone=p,order_status="paid",delivery_status="pending",noofitems=i.quantity)
                 i.products.stock=i.products.stock-i.quantity
                 i.save()
                 o.save()
             cart.delete()
             msg="Ordered Successfully"
             return render(request, 'orderdetails.html',{'msg':msg,'total':total})
        else:
            msg="Insufficient Amount. You cannot place order"
            return render(request, 'orderform.html')

    return render(request,'orderform.html')

@login_required()
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status="paid")
    return render(request,'orderview.html',{'o':o,'name':u.username})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ecommerce</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--    google font link-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">

<!--    font-awesome link for icons-->
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

</head>
<body>
<CENTER><h2 style="color:Purple;font-weight:bold;"><img src="{% static 'img/logo.jpg' %}" alt="img" height="100px" width="130px">SHOPsY</h2></CENTER>
<div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fs-5 bolder">
  <div class="container-fluid">
    <a class="navbar-brand fs-5" href="#">Myshop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>
                  <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i style="font-size:20px;" class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
        </li>

          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>

           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          {% endif %}
        </ul>

      <form method="POST" class="d-flex" action="{% url 'search:searchresult' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div>
{% block content %}
{% endblock %}
    <footer class="footer">
    <div style="background-color:white;text-align:center;font-weight:bold;color:green;height:60px;width:100%;position:fixed;bottom:0;left:0;">
        <p><i class="fa-regular fa-copyright"></i> Shopsy pvt ltd.All rights reserved</p>
    </div>
</footer>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid">
    {% if not cart %}
    <div class="text-center" style="margin-bottom:100px">
        <h1 class="text-center">Cart is Empty</h1>
        <strong><a href="{% url 'shop:home' %}" class="btn btn-primary ">Continue Shopping</a> </strong>
    </div>

     {% else%}


<div class="row">
    <h1 class="text-center">Shopping cart</h1>
  <div class="col-sm-6">
    <table class="table table-bordered">
     <tr>
      <th colspan="5" class="text-center"> cart items</th>
       {% for i in cart %}
     </tr>
     <tr>
      <td><img src="{{i.products.image.url}}" height="100px" width="100px"></td>
      <td><strong>{{i.products.name}}</strong></td>
      <td>
          <p><strong>ProductsId:</strong>{{i.products.id}}</p>
      <p><strong>Unit Price:</strong>{{i.products.price}}</p>
      <p><strong>Quantity:</strong>{{i.quantity}}*{{i.products.price}}</p>
      </td>
         <td>Subtotal:{{i.subtotal}}</td>
         <td>
             {% if i.quantity < i.products.stock %}
             <a href="{% url 'cart:add_cart' i.products.id %}"><i class="fa-solid fa-circle-plus text-success"></i></a>
             <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus text-primary"></i></a>
             <a href="{% url 'cart:delete_cart' i.products.id %}"><i class="fa-solid fa-trash text-danger"></i></a>

             {% else %}
             <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus text-primary"></i></a>
             <a href="{% url 'cart:delete_cart' i.products.id %}"><i class="fa-solid fa-trash text-danger"></i></a>
             {% endif %}

         </td>
     </tr>
        {% endfor %}
    </table>
  </div>
    <div style="position:relative;" class="col-sm-6 col-lg-6 col-xs-6 col col-md-6">
        <table class="table table-bordered" style="width:400px;right:0px;left:700px;">
            <tr><th colspan="5" class="text-center">Check Out</th></tr>
            <tr><th class="text-center">Total price:{{total}}</th></tr>

    </table>
        <a href="{% url 'shop:home' %}" class="btn btn-secondary">Continue Shopping</a>
        <a href="{% url 'cart:orderform' %}" style="position:absolute;right:0;" class="btn btn-success">Place Order</a>
    </div>

</div>
    {% endif %}
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h4>{{user.username}}</h4>
{% else %}
<h4>visitor</h4>
{% endif %}
<img src="{% static 'img/shop.jpg' %}" alt="img" height="800px" width="100%">
<div class="container-fluid" style="margin-bottom:100px;">
    <h2 class="text-center" style="color:red;font-weight:bold;">COLLECTIONS</h2>
    <br>
    <p style="text-align:justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>

<div class="container-fluid">
    <div class="row">
        {% for i in c %}
        <div class=" col-md-4" style="height:450px">
            <div class="card" style="background:#b39ddb">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="color:green">
                 <h5 class="card-title text-center" style="text-transform:uppercase;">{{i.name}}</h5>
                <a href="{% url 'shop:allproducts' i.slug %}" class="btn btn-outline-light" style="background:purple;position:relative;left:38%;">PRODUCTS</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 mt-5">
        <img src="{{p.image.url}}" height="400px" width="500px"></div>
        <div class="col-sm-6 mt-5">
        <h2>{{p.name}}</h2>
        <h3>Price:{{p.price}}</h3>
            <h3>Product Description</h3>
            <p style="text-align:justify">{{p.description}}</p>
            {% if p.stock <= 0 %}
            <h2>Out of Stock</h2>
            {% else %}
            <a href="{% url 'cart:add_cart' p.id %}" class="btn btn-primary">ADD TO CART</a>
        {% endif %}
        </div></div></div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<h2>log in</h2>
<div >
<form method="POST" enctype="multipart/form-data" class="form form-center p-2 " style="width:35%">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter Username">
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter password">
    </div>
    <div class="mb-3">
        <center><input type="submit" class="btn btn-primary" value="login"></center>
    </div>
</form>
    {% if messages %}
    {% for i in messages%}
    <ul class="messages">
        <li>{{i}}</li>
    </ul>
    {%endfor%}
    {% endif%}
</div>
{% endblock%}

ecommerce/templates/orderdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
<h2 class="text-center text-success">{{msg}}</h2>
<h5 class="text-center text-danger">Thank you....</h5>
    <p class="text-center"><a href="{% url 'shop:home' %}">Continue Shopping</a></p>
</div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form method="POST" enctype="multipart/form-data" class="form form-center p-2 " style="width:35%">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" name="a" placeholder="Enter address">
    </div>
    <div class="mb-3">
        <label class="form-label">Phone</label>
        <input type="text" class="form-control" name="p" placeholder="Enter phone number">
    </div>
         <div class="mb-3">
        <label class="form-label">Accountnumber</label>
        <input type="text" class="form-control" name="c" placeholder="Enter account number">
    </div>
    <div class="mb-3">
        <center><input type="submit" class="btn btn-primary" value="Submit"></center>
    </div>
</form>
</div>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h5 class="text-center">Name of the customer: {{name}}</h5>
        {% for i in o %}
        <div class="col-sm-3 py-3" style="border:2px solid pink">
            <center><img src="{{i.products.image.url}}" height="150px" width="150px"></center>
        </div>
        <div class="col-sm-7 py-3 text-center" style="border:2px solid pink">
            Delivery Address :{{i.address}}<br>
            Phone number :{{phone}}<br>
            {{i.products.name}}<br>
            {{i.products.price}}<br>
            Quantity Ordered :{{i.noofitems}}<br>
            Subtotal :{{i.subtotal}}<br>
            <strong class="text-primary">Ordered on {{i.date_added}}</strong><br>
            <strong class="text-success">Delivery status :{{i.delivery_status}}</strong>
        </div>
        {% endfor %}
    </div></div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
<img src="{{c.image.url}}" alt="img" height="400px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h2 class="text-center" style="color:red;font-weight:bold;">{{c.name}}</h2>
    <br>
    <p style="text-align:justify">{{c.description}}</p></div>

<div class="container-fluid">
    <div class="row">
        {%for i in p %}
        <div class=" col-md-4" style="height:450px">
            <div class="card" style="background:#b39ddb">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="color:green">
                 <h5 class="card-title text-center" style="text-transform:uppercase;">{{i.name}}</h5>
                    <h6 class="card-title text-center" style="text-transform:uppercase;">{{i.price}}</h6>
                <a href="{% url 'shop:viewproduct' i.slug %}" class="btn btn-outline-light" style="background:purple;position:relative;left:38%;">DETAILS</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<h2>register</h2>
<div class="container" style="margin-bottom:100px;">
<form method="POST" class="p-2 " enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Username">
  </div>
    <div class="mb-3">
    <label class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="Enter first name">
  </div>
    <div class="mb-3">
    <label class="form-label">last name</label>
    <input type="text" class="form-control" name="l" placeholder="Enter last name">
  </div>
    <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="Enter Email">
  </div>
    <div class="mb-3">
    <label class="form-label">password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter password">
  </div>
   <div class="mb-3">
    <label class="form-label">confirm password</label>
    <input type="password" class="form-control" name="cp" placeholder="Enter password again">
 </div>
    <div class="mb-3">
    <input type="submit" class="btn btn-primary">

    </div></form></div>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock%}

ecommerce/templates/searchresult.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    <h4 class="text-center">You have searched for {{ query }}</h4>
</div>

<div class="container">
    <div class="row">
        <h6 class="text-center">SEARCH RESULT</h6>
        {%for i in products %}
        <div class=" col-md-4" style="height:450px">
            <div class="card" style="background:#b39ddb">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="color:green">
                 <h5 class="card-title text-center" style="text-transform:uppercase;">{{i.name}}</h5>
                    <h6 class="card-title text-center" style="text-transform:uppercase;">{{i.price}}</h6>
                <a href="{% url 'shop:viewproduct' i.slug %}" class="btn btn-outline-light" style="background:purple;position:relative;left:38%;">DETAILS</a>
                </div>
            </div>
        </div>
        {% empty %}
        <h5 class="text-center">0 Result Found</h5>
        {% endfor %}
    </div>
</div>
{% endblock %}